config/routes.rb
Bitewolf::Application.routes.draw do
  root :to => "users#show"

  devise_for :users

  resources :users
  resources :invitations do
    member do
      get 'accept'
    end
  end

  resources :groups do
    resources :lunches do
      resources :locations do
        member do
          get 'vote'
        end
      end
    end
  end

end

app/models/group.rb
class Group
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type:String
  field :description, type:String
  field :last_rand, type:String

  has_and_belongs_to_many :users
  embeds_many :lunches
  has_many :invitations

  validates_uniqueness_of :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(params[:group])
    @group.users.push(current_user)

    if @group.save
      redirect_to(@group, :notice => 'Created.')
    else
      render :action => "new"
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update_attributes(params[:group])
      redirect_to(@group, :notice => 'Updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    redirect_to :action => "index"
  end

  def invite
  end

  def send_invitation
  end
end

app/views/groups/edit.html.haml
%h2 Edit group
= form_for(@group) do |g|
  %div
    = g.label :name
    %br/
    = g.text_field :name, :autofocus => true
  %div
    = g.label :description
    %br/
    = g.text_area :description
  %div= g.submit "Update"

app/views/groups/index.html.haml
%h1= current_user.username + "'s groups"
= link_to "create a new group", new_group_path
%br/
= link_to "create a new group and lunch simultaneously", nil
%ul
  - @groups.each do |g|
    %li
      = link_to g.name, group_path(g.id)
      %ul
        %li
          = "members: " + g.users.count.to_s
        %li
          = "lunches: " + g.lunches.count.to_s
        %li
          = link_to "edit", edit_group_path(g.id)
        %li
          = link_to "delete", group_path(g.id), :confirm => "are you sure you want to remove?", :method => :delete

app/views/groups/new.html.haml
%h1 Create group
= form_for(@group) do |g|
  %div
    = g.label :name
    %br/
    = g.text_field :name, :autofocus => true
  %div
    = g.label :description
    %br/
    = g.text_area :description
  %div= g.submit "Create"

app/views/groups/show.html.haml
%h1= @group.name
%p= @group.description
= link_to "invite someone to this group", new_invitation_path
%br/
= link_to "add a lunch", new_group_lunch_path(@group.id)
%h2= "members (" + @group.users.count.to_s + ")"
%ul
  - @group.users.each do |u|
    %li
      = link_to u.username, user_path
%h2 lunches
%ul
  - @group.lunches.each do |l|
    %li
      = link_to l.time + " " + l.day, group_lunch_path(@group.id, l.id)
      = link_to "delete", group_lunch_path(@group.id, l.id), :confirm => "are you sure you want to remove?", :method => :delete
      %ul
        - l.locations.each do |o|
          %li
            = o.restaurant + " - " # + o.style.gsub("_", " ")
            = link_to "▲", vote_group_lunch_location_path(@group.id, l.id, o.id, :vote => "up"), :class => "voteable"
            = link_to "▼", vote_group_lunch_location_path(@group.id, l.id, o.id, :vote => "down"), :class => "voteable"
            %ul
              %li
                = "upvotes: " + o.upvotes.count.to_s
              %li
                = "downvotes: " + o.downvotes.count.to_s
              %li
                - if o.upvotes.count > @group.users.count / 2
                  = "accepted? yes"
                - else
                  = "accepted? no"
= link_to "back to profile", user_path(current_user.id)