config/routes.rb
Bitewolf::Application.routes.draw do
  root :to => "users#show"

  devise_for :users

  resources :users
  resources :invitations do
    member do
      get 'accept'
    end
  end

  resources :groups do
    resources :lunches do
      resources :locations do
        member do
          get 'vote'
        end
      end
    end
  end

end

app/models/lunch.rb
class Lunch
  include Mongoid::Document
  include Mongoid::Timestamps

  field :day, type:String
  field :time, type:String
  field :time_message, type:String
  field :upvotes_count, type:Integer
  field :chosen_location_id, type:String
  field :chosen_by, type:Symbol
  field :choser_id, type:String

  embedded_in :group
  embeds_many :locations

  def complete?
    # time_diff = (DateTime.now - DateTime.strptime(self.day + " " + self.time, '%m/%d/%Y %H:%M %p')) * 24 * 60
    # self.tallied? && self.chosen_by == :vote || time_diff <= 60
    false
  end

  def tallied?
    self.chosen_location_id != nil
  end

  def sort_locations_by_upvotes!
    self.locations.sort! do |x, y|
      y.upvotes.count <=> x.upvotes.count
    end

    self
  end

  def remove_voter_upvotes!(voter)
    deleted = false
    self.locations.map! do |location|
      if location.upvotes.delete(voter)
        deleted = true
      end
      location
    end

    self.save
    deleted
  end

  def count_upvotes
    self.locations.reduce(0) do |memo, item|
      memo += item.upvotes.count
    end
  end

  def voting_complete?
    self.count_upvotes == self.group.users.count
  end

  def decide_winner
    max_votes = self.locations.map{|l| l.upvotes.count}.max

    top_locations = self.locations.reduce([]) do |arr, loc|
      if loc.upvotes.count == max_votes
        arr << loc
      end
      arr
    end

    if top_locations.count > 1
      if self.chosen_location_id != nil
        self.chosen_location_id = nil
        self.chosen_by = nil
      end

      # rand_location = top_locations[rand(0...top_locations.count)]

      # self.chosen_location_id = rand_location.id
      # self.chosen_by = :rand
      # self.group.last_rand = rand_location.suggester_id
    else
      self.chosen_location_id = top_locations.first.id
      self.chosen_by = :vote
    end

    self.save
  end

  def tally
    if self.voting_complete?
      self.decide_winner
    else
      if self.chosen_location_id != nil
        self.chosen_location_id = nil
        self.chosen_by = nil
        self.save
      end
    end
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @lunch = Lunch.new
  end

  def index
    @lunches = current_user.groups.find(params[:group_id]).lunches
  end

  def show
    @group = current_user.groups.find(params[:group_id])
    @lunch = @group.lunches.find(params[:id]).sort_locations_by_upvotes!

    @lunch.tally
  end

  def create
    @lunch = Lunch.new(params[:lunch])
    @lunch.time_message = "Initial time (#{current_user.username})"
    @group = current_user.groups.find(params[:group_id])

    @location = Location.new(:restaurant => params[:restaurant], :style => params[:style])
    @location.upvotes = [current_user.id]
    @location.downvotes = []

    if @lunch.locations << @location && @group.lunches << @lunch
      redirect_to(@group, :notice => 'Created.')
    else
      render :action => "new"
    end
  end

  def update
    @group = current_user.groups.find(params[:group_id])
    @lunch = @group.lunches.find(params[:id])
    params[:lunch][:time_message] << " (#{current_user.username})"

    if @lunch.update_attributes(params[:lunch])
      redirect_to([@group, @lunch], :notice => 'Updated the time.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @group = current_user.groups.find(params[:group_id])
    @group.lunches.find(params[:id]).destroy
    redirect_to(@group, :notice => 'Deleted.')
  end
end

app/views/lunches/new.html.haml
= javascript_include_tag "jquery.ui.timepicker.js"
= stylesheet_link_tag "jquery-ui"

%h1 New lunch
= form_for([:group, @lunch]) do |l|
  %div
    = l.label :day
    %br/
    = l.text_field :day
  %div
    = l.label :time
    %br/
    = l.text_field :time
  %div
    = l.label :restaurant
    %br/
    = text_field_tag 'restaurant'
  %div
    = l.label :style
    %br/
    = select_tag('style', options_for_select([["take out", "take_out"], ["eat in", "eat_in"]]), { :include_blank => true })
  %div= l.submit "Create"

app/views/lunches/show.html.haml
%h1= "food @ " + @lunch.time + " " + @lunch.day
= form_for([@group, @lunch], :method => :put) do |f|
  %div
    = f.label :time
    %br/
    = f.text_field :time, :value => @lunch.time
    %span= @lunch.time_message
  %div
    = f.label :time_message
    %br/
    = f.text_field :time_message, :value => ""
  %div= f.submit "Update"
%br/
= link_to "suggest a different spot", new_group_lunch_location_path(@group.id, @lunch.id)
-# - if @lunch.tallied?
-#   %h2 complete!
-#   - if @lunch.chosen_by == :vote
-#     %h3 chosen by majority vote
-#   - else
-#     %h3 chosen by random draw
-#     %p
-#       = "There seemed to be a tie, so bitewolf made an executive decision."
%ul
  - @lunch.locations.each do |o|
    - if o.id.to_s == @lunch.chosen_location_id
      %div{:style => "display:inline-block;border:5px solid green;"}
        %li
          = o.restaurant + " - " + o.style.gsub("_", " ")
          = link_to "▲", vote_group_lunch_location_path(@group.id, @lunch.id, o.id, :vote => "up"), :class => "voteable"
          %ul
            %li
              = "upvotes: " + o.upvotes.count.to_s
            %li
              = "downvotes: " + o.downvotes.count.to_s
            %li
              = "accepted? no"
    - else
      %div
        %li
          = o.restaurant
          = " - " + o.style.gsub("_", " ") if o.style
          = link_to "▲", vote_group_lunch_location_path(@group.id, @lunch.id, o.id, :vote => "up"), :class => "voteable"
          %ul
            %li
              = "upvotes: " + o.upvotes.count.to_s
            %li
              = "downvotes: " + o.downvotes.count.to_s
            %li
              = "accepted? no"
= link_to "back to groups", group_path(@group.id)